### ISSUE TITLE
Different packages with the same name

### ISSUE THREAD

**Issue by bsilver8192** [horizon-eda/horizon-pool-convention#12]
I've recently realized that NXP and Diodes Incorporated have two different packages called SOD123F. They're similar, but I think they're different enough to want different land patterns. I've created a footprint for the NXP version, with an eye towards contributing it to horizon-pool, and I'm not sure what to call it. I started with `packages/diode/SOD123F` similar to the existing `packages/diodes/SOD123`, but after realizing there were two versions I'm not so sure.

[NXP's document](https://www.nxp.com/docs/en/package-information/SOD123F.pdf) recommends a pad width of 1.2mm. The [Diodes document](https://www.diodes.com/assets/Package-Files/SOD123F.pdf) says the maximum lead width is 1.05mm, so their recommended pad width is 1.8mm. Those are far enough apart I'm not sure it's reasonable to use the same package for both of them.

Looking at documents from a few other companies, it seems like NXP is the odd one out. Maybe that points to `packages/manufacturer/nxp/SOD123F_nxp` being the preferred answer? Or would it be `packages/manufacturer/nexperia/SOD123F_nexperia`?

**Comment by fruchti** [comment]
Sorry for the late reply. This is a very good point and currently left unclear by the convention!

If manufacturers disagree significantly on some dimension for an otherwise common package or its land pattern, the package shouldn’t be added as generic. If there’s a clear ‘odd one out’ like in your case, I’d say the NXP one is a manufacturer-specific package as much as the pool is concerned, while all other would be consolidated into one generic package.

There’s no need to add the manufacturer to the package’s file name, though. The package has a manufacturer field, which is also shown in the pool browser, and the file name is unique because it’s in the manufacturer-specific package directory.

I’m not completely up to date on who is actually producing these semiconductors, i.e. if it’s Nexperia or NXP. I mean, you could also say that EDA component libraries pretty much always lag behind the latest silicon company mergers, so choose as you see fit. Renaming files in the pool later isn’t a problem for projects depending on the entries anyway.
